export const PAYMENTGATEWAY_METHODS_CASHIN = [
  // { id: "QRPH", name: "QRPH", icon: "/payment-gateway/qrph.png" },
  { id: "GCash", name: "GCash", icon: "/payment-gateway/gcash.png" },
  {
    id: "QRPH-RAN",
    name: "QRPH-RAN",
    icon: "/payment-gateway/QR-Ran-Online.png",
  },
  { id: "Maya", name: "Maya", icon: "/payment-gateway/maya.png" },
];

export const PAYMENT_METHODS_CASHIN = [
  { id: "QRPH-RAN", name: "QRPH-RAN", icon: "/logo/qr-logo.png" },
  { id: "QRPH", name: "QRPH", icon: "/logo/qr-logo.png" },
  { id: "GoTyme", name: "GoTyme", icon: "/logo/gotyme-logo.png" },
  { id: "Chat-Based", name: "Chat-Based", icon: "/logo/chat-based-logo.png" },
];

export const PAYMENT_METHODS_CASHOUT = [
  { id: "GCash/Maya", name: "GCash/Maya", icon: "/logo/gcashmaya-logo.png" },
  {
    id: "BankTransfer",
    name: "Bank Transfer",
    icon: "/logo/banktransfer-logo.png",
  },
];

export const E_WALLET_BANK = ["GCash", "MAYA"];
export const BANK_ONLY = [
  "GoTyme",
  "Landbank",
  "BDO",
  "BPI",
  "Metrobank",
  "PNB",
  "CitiBank",
  "UnionBank",
  "RCBC",
  "Security",
  "EastWest",
  "China",
  "Maybank",
];

export const QUICK_AMOUNTS = [100, 150, 200, 300, 500, 1000];

export const DPAY_BANK_CASHOUTS = [
  {
    Name: "Asia United Bank Corporation",
    Description: "PH_AUB",
    Code: "PH_AUB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Banco De Oro Unibank, Inc",
    Description: "PH_BDOU",
    Code: "PH_BDO",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Bank of Commerce, Inc.",
    Description: "PH_BOC",
    Code: "PH_BOC",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "BPI / VYBE by BPI",
    Description: "PH_BPI",
    Code: "PH_BPI",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "BDO Network Bank, Inc.",
    Description: "PH_BDONB",
    Code: "PH_BDONB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "BDO Unibank, Inc.",
    Description: "PH_BDO",
    Code: "PH_BDO",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "BPI / BPI Family Bank",
    Description: "PH_BPI",
    Code: "PH_BPI",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "BPI Direct Banko, Inc., A Savings Bank",
    Description: "PH_BDBI",
    Code: "PH_BDBI",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Cebuana Lhuillier Bank / Cebuana Xpress",
    Description: "PH_CLRB",
    Code: "PH_CLRB",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "China Bank Savings, Inc.",
    Description: "PH_CBS",
    Code: "PH_CBS",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "China Banking Corporation",
    Description: "PH_CBCN",
    Code: "PH_CBCN",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "East West Banking Corporation",
    Description: "PH_EWB",
    Code: "PH_EWB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "East West Rural Bank / Komo",
    Description: "EAWRPHM2XXX",
    Code: "EAWRPHM2XXX",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "East West Rural Bank, Inc.",
    Description: "PH_EWBRB",
    Code: "PH_EWBRB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "G-Xchange / GCash",
    Description: "PH_GXI",
    Code: "PH_GXI",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "GrabPay",
    Description: "PH_GBY",
    Code: "PH_GBY",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "LANDBANK / OFBank",
    Description: "PH_LBP",
    Code: "PH_LBP",
    Status: true,
    IsEWallet: true,
  },

  {
    Name: "Maya / Paymaya Philippines, Inc.",
    Description: "PH_PMP",
    Code: "PH_PMP",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "Maybank Philippines, Inc.",
    Description: "PH_MAYBANK",
    Code: "PH_MAYBANK",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Palawan Pay",
    Description: "PH_PALP",
    Code: "PH_PALP",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "Philippine Digital Asset Exchange, Inc., / PDAX",
    Description: "PDAXPHM2XXX",
    Code: "PDAXPHM2XXX",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "Philippine National Bank",
    Description: "PH_PNB",
    Code: "PH_PNB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Philippine Savings Bank",
    Description: "PH_PSB",
    Code: "PH_PSB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "RCBC/DiskarTech",
    Description: "PH_RCBC",
    Code: "PH_RCBC",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "Rizal Commercial Banking Corporation",
    Description: "PH_RCBC",
    Code: "PH_RCBC",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Robinsons Bank",
    Description: "PH_RSB",
    Code: "PH_RSB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Security Bank Corporation",
    Description: "PH_SB",
    Code: "PH_SB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "ShopeePay Philippines Inc.",
    Description: "PH_SPPI",
    Code: "PH_SPPI",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "UCPB Savings Bank, Inc.",
    Description: "PH_UCPBSB",
    Code: "PH_UCPBSB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "Union Bank of the Philippines",
    Description: "PH_UB",
    Code: "PH_UB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "United Coconut Planters Bank",
    Description: "PH_UCPB",
    Code: "PH_UCPB",
    Status: true,
    IsEWallet: false,
  },
  {
    Name: "UNOBANK INC",
    Description: "7034",
    Code: "7035",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "Wise Pilipinas Inc",
    Description: "TRWIPHM2XXX",
    Code: "TRWIPHM2XXX",
    Status: true,
    IsEWallet: true,
  },
  {
    Name: "GoTymeBank",
    Description: "PH_GTB",
    Code: "PH_GTB",
    Status: true,
    IsEWallet: true,
  },
];
